Repository ti-community-infra/configs, pull requests merged in 2020-12, with the labels that each got.

#25 config: enable more plugins for community repo
  prow/config/plugins.yaml
Labels: size/XS

#26 config: remove travis-ci
  prow/config/config.yaml
Labels: size/XS, status/LGT1

#27 config: use default trigger setting
  prow/config/plugins.yaml
Labels: size/XS

#28 config: enable more configs for community repos
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S

#29 config: fix community repos branch protection 9a87871
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S

#31 config: require statics check in pd
  prow/config/config.yaml
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#30 config: Update labels.yaml for introducing tiup
  prow/cluster/label_sync.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: ok-to-test, size/XXL, status/LGT1, status/can-merge

#33 config: add previous label for good first issue
  prow/config/labels.yaml
Labels: size/XS

#34 feat: support org peribolos
  .gitignore
  .prow.yaml
  cmd/merge/main.go
  go.mod
  go.sum
  orgs/.gitignore
  orgs/config_test.go
  orgs/tidb-community-bots/bots-test/teams.yaml
  orgs/tidb-community-bots/collaborators/teams.yaml
  orgs/tidb-community-bots/org.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/peribolos.yaml
  prow/config/config.yaml
  prow/config/labels.yaml
  scripts/peribolos.sh
Labels: size/XXL, status/LGT1, status/can-merge

#35 build: bump ti-community-prow plugins and config tiup
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/config/external_plugins_config.yaml
Labels: size/S, status/LGT1, status/can-merge

#36 chore: rename prow-configs to configs
  .prow.yaml
  README.md
  go.mod
  orgs/tidb-community-bots/collaborators/teams.yaml
  prow/cluster/label_sync.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/M

#37 fix: log the error
  cmd/merge/main.go
Labels: size/S, status/LGT1, status/can-merge

#38 build: bump version
  .prow.yaml
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#39 config: enable lifecycle for tiup
  prow/config/plugins.yaml
Labels: size/XS, status/LGT1, status/can-merge

#40 config: enable milestone for ti-community-prow
  prow/config/plugins.yaml
Labels: size/S

#42 config: enable label plugins for pd
  prow/cluster/label_sync.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#45 ci: add post-configs-label-sync
  .prow.yaml
  prow/cluster/label_sync.yaml
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge

#46 fix: refine typo
  .prow.yaml
  prow/config/labels.yaml
Labels: size/XS

#47 ci: add pull-configs-validate-labels-yaml
  .prow.yaml
  prow/config/labels.yaml
Labels: size/XXL

#48 config: enable hold and wip for tikv pd repo
  prow/config/plugins.yaml
Labels: size/XS, status/LGT1, status/can-merge

#52 config: update ti-community-prow milestone
  prow/config/plugins.yaml
Labels: size/XS, status/LGT1, status/can-merge

#53 config: disable label_sync for tiup
  .prow.yaml
  prow/config/labels.yaml
Labels: size/L, status/LGT1, status/can-merge

#54 config: disable tars for ti-community-prow
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS

#55 config: update ti-community-prow milestone
  prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#58 fix: refine ti-community-infra name
  orgs/ti-community-infra/bots-test/teams.yaml
  orgs/ti-community-infra/collaborators/teams.yaml
  orgs/ti-community-infra/org.yaml
Labels: size/XS, status/can-merge

#59 config: add teams for ti community infra
  orgs/ti-community-infra/collaborators/teams.yaml
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/M

#61 config: fix typo
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/XS

#64 config: update ti-community-prow milestone
  prow/config/plugins.yaml
Labels: size/XS

#69 build: bump prow version
  .prow.yaml
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1

#72 config: add branches configuration item for tidb-operator
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#73 config: add lifecycle-periodics.yaml
  .prow.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/lifecycle-periodics.yaml
Labels: size/L, status/LGT1, status/can-merge

#74 build: mount the jobs
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/jobs/ti-community-infra/lifecycle-periodics.yaml
Labels: size/M

#75 config: enable trigger for tikv to test rerere
  prow/config/plugins.yaml
  prow/jobs/tikv/tikv/tikv-presubmits.yaml
Labels: do-not-merge/hold, size/M

#76 config: fix tikv rerere jobs name
  prow/jobs/tikv/tikv/tikv-presubmits.yaml
Labels: size/XS

#79 config: fix outdated milestone team
  prow/config/plugins.yaml
Labels: size/XS

#81 config: add ti-community-infra/test-dev permissions
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/XS

#80 config: add qa-release-merge as a trusted team for the pd release branch
  prow/config/external_plugins_config.yaml
Labels: sig/scheduling, size/S, status/LGT1, status/can-merge

#82 config: remove tikv jobs
  prow/jobs/tikv/tikv/tikv-presubmits.yaml
Labels: size/M

#83 build: bump plugins version from v0.16.5 to v0.16.6
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#85 config: add pull-ti-community-prow-rerere for ti-community-prow
  prow/config/config.yaml
Labels: size/XS

#86 build: bump plugins version from v0.16.6 to v0.16.7
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#84 config: enable prow for tikv
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, status/LGT1, status/can-merge
