Repository ti-community-infra/configs, pull requests merged in 2021-09, with the labels that each got.

#421 config: one member retire from community-infra reviewer team
  orgs/ti-community-infra/community-infra-reviewers/teams.yaml
  orgs/ti-community-infra/org.yaml
Labels: status/LGT1, status/can-merge, size/XS

#422 build: bump prow version from v20210723-55eee17612 to v20210806-c95403cd67
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#423 build: bump ti plugins version from v1.8.1 to v1.8.2
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#424 config: Revert "build: bump ti plugins version from v1.8.1 to v1.8.2 (#423)"
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#425 build: bump ti plugins version from v1.8.1 to v1.8.3
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#426 config: add label for sig/bigdata for doc repos
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#427 config(tidb): add check-license required status check for tidb repo
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#428 config(tidb): remove check-license from release branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#429 config: add tisonkun to community-infra-team
  orgs/ti-community-infra/community-infra-committers/teams.yaml
  orgs/ti-community-infra/community-infra-maintainers/teams.yaml
  orgs/ti-community-infra/community-infra-reviewers/teams.yaml
  orgs/ti-community-infra/org.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#420 config(tidb): enable blockade for tidb repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#431 config(parser): replace circle ci by jenkins verify ci
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#432 revert: "config(tidb): enable blockade for tidb repo"
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#430 config: change the requested reviewer for docs-dm repo
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#434 fix: fix the labels config for tidb repo
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#436 config(tidb): enable require code owner reviews
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#437 config: stop autocc for ticdc
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#438 config: add CLA as required status check for tidb-tools
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#439 config: add autobumper for tichi repo
  .gitignore
  prow/autobump-config/tichi-prow-component-autobump-config.yaml
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/L

#440 config: add auto bumper for configs
  prow/autobump-config/configs-prow-component-autobump-config.yaml
  prow/jobs/ti-community-infra/configs/configs-periodics.yaml
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/M

#441 config(docs-cn,docs): Replace cirlcleci/circleci: lint with jenkins-docs-cn/verify for required_status_checks
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution
