Repository ti-community-infra/configs, pull requests merged in 2021-05, with the labels that each got.

#282 config: enable cherrypicker for ticdc
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#283 config: enable cherrypicker for dm
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#284 config: enable cherrypicker for br
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#285 build: bump all ti plugins from v1.5.9 to v1.5.10
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_cherrypicker_service.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#286 config: enable cherry-pick-approved label to lonng
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/M, status/LGT1, status/can-merge

#288 config: enable tars for tidb dashboard
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/diagnosis, size/XS, status/LGT1, status/can-merge

#291 build: bump all ti plugins from v1.5.10 to v1.5.11
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S

#292 config: enable cherry-pick-unapproved for tidb
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#293 config: clean up 5.0-rc configurations
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/L, status/LGT1, status/can-merge

#294 config: Enable cherry-pick-unapproved for forced frozen repos
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#296 chore: appending inactive reviewers
  prow/config/external_plugins_config.yaml
Labels: contribution, needs-ok-to-test, size/M, status/LGT1, status/can-merge

#299 config: enable cherrypicker for docs-cn and docs
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/L, status/LGT1, status/can-merge

#300 config: enable cherrypicker for docs-dm and docs-tidb-operator
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/M, status/LGT1, status/can-merge

#298 config: br not require every PR to use the latest base
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#301 config: enable tichi for chaos-mesh/website
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/L, status/LGT1, status/can-merge

#304 fix: Do not remind for missing labels on the release branch
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/S, status/LGT1, status/can-merge

#302 config: Add labels for chaos-mesh/website
  prow/config/labels.yaml
Labels: contribution, needs-ok-to-test, sig/community-infra, sig/docs, size/XL, status/LGT1, status/can-merge

#305 config: Make the tide required for SIG-docs repositories
  prow/config/config.yaml
Labels: sig/community-infra, sig/docs, size/S, status/LGT1, status/can-merge

#287 config: enable release-note for pd
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#306 config: enable blockade and label for chaos-mesh/website and chaos-mesh/website
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/M, status/LGT1, status/can-merge

#308 fix: enable label sync for chaos-mesh/website and chaos-mesh/website-zh
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/XS

#309 fix: trigger the label sync
  prow/config/labels.yaml
Labels: size/XS

#312 build: bump all ti plugins from v1.5.11 to v1.5.12
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#313 config: update the list of auto-assigned reviewers for pd
  prow/config/external_plugins_config.yaml
Labels: contribution, ok-to-test, size/M, status/LGT1, status/can-merge

#314 config: update the list of auto-assigned reviewers for pingcap/dm
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#315 config: update the list of auto-assigned reviewers for four docs repos
  prow/config/external_plugins_config.yaml
Labels: contribution, ok-to-test, sig/community-infra, sig/docs, size/L, status/LGT1, status/can-merge

#316 chore: update the reviewer of chaos-mesh
  prow/config/external_plugins_config.yaml
Labels: contribution, needs-ok-to-test, size/M, status/LGT1, status/can-merge

#318 config: update the list of auto-assigned reviewers for pingcap/dumpling
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/S, status/LGT1, status/can-merge

#319 config: update the list of auto-assigned reviewers for ticdc
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/S, status/LGT1, status/can-merge

#320 config: update the list of auto-assigned reviewers for tidb-tools
  prow/config/external_plugins_config.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#322 build: cleanup plank and bump all components version
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/plank_rbac.yaml
  prow/cluster/plank_service.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
  prow/jobs/tikv/tikv/tikv-bot-periodics.yaml
Labels: size/L, status/LGT1, status/can-merge

#321 config: disable release-note for tichi
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/XS, status/LGT1, status/can-merge

#317 config: remove some slow check from "Required"
  prow/config/config.yaml
Labels: contribution, needs-ok-to-test, sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#323 config: update the list of auto-assigned reviewers for BR
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/S, status/LGT1, status/can-merge

#324 config: update the list of auto-assigned reviewers for tidb-operator
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, sig/community-infra, sig/k8s, size/S, status/LGT1, status/can-merge

#325 config: cleanup check_release_note CI config for pd
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#328 config: remove several required check in ticdc release-5.0
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#326 config: enable release-note for tikv && cleanup check_release_note CI config for tikv
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#327 config: Add the v5.1 label for the docs-cn and docs repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#329 config: disable auto-retester for tidb and tikv
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
  prow/jobs/tikv/tikv/tikv-bot-periodics.yaml
Labels: size/L, status/LGT1, status/can-merge

#330 config: Retire me from ti-community-infra admin
  orgs/ti-community-infra/bots-test/teams.yaml
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/org.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/S, status/LGT1, status/can-merge

#331 config: fix the broken org config
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/XS, status/LGT1, status/can-merge

#332 build: upgrade go version to 1.16
  go.mod
  go.sum
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/L, status/LGT1, status/can-merge

#333 build: bump all ti plugins from v1.5.12 to v1.5.13
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#334 config: auto respond to lgtm
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/L, status/LGT1, status/can-merge
