Repository ti-community-infra/configs, pull requests merged in 2021-08, with the labels that each got.

#387 config(ticdc): remove some required_status_checks in release-4.0
  prow/config/config.yaml
Labels: contribution, needs-ok-to-test, size/XS, status/LGT1, status/can-merge

#390 config(ticdc): ignore the can-merge and ptal labels
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#391 config(ticdc): Add me to the auto-cc list
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#389 config: Add the v5.2 label for the docs-cn and docs repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#392 config: add cherry-pick-approved trusted users
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#393 config: add exclude labels for tars
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#394 config(dumpling): update dumpling integration test requirements
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#395 config: enable tichi for tics
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/L, sig/community-infra, sig/bigdata

#396 config: enable re-trigger test on tics
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S, sig/community-infra, sig/bigdata

#397 config(dumpling): update dumpling integration test requirements for release branches
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, needs-ok-to-test, contribution

#398 config(ticdc): Add release-5.2 branch related configuration
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, sig/community-infra, sig/migrate

#399 config: modify cherry_pick_unapproved branch regexp for 5.x
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#400 build: bump all components version from v20210701-3efe91b8cd to v20210723-55eee17612
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#401 build: bump all ti plugins version to v1.7.2
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#402 feat: add release 5.2 config for tics
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#404 feat: enable cherry-pick-unapproved for tics
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S, sig/community-infra, sig/bigdata

#405 config(tools): refine label-blocker configuration for tools
  prow/config/external_plugins_config.yaml
Labels: size/S

#406 config: Retire from ti-community-infra
  orgs/ti-community-infra/org.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: status/LGT1, status/can-merge, size/XS

#407 feat: add release-5.2 config for some repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/L

#408 fix: parser no need cherry-pick-approved
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#410 config(dumpling): update dumpling integration test requirements
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution, first-time-contributor

#411 config: add the bot configuration for v5.2 branch in two doc repos
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#412 config: add cherry-pick labels for the docs repo
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#415 build: bump ti plugins to v1.8.0
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/config/external_plugins_config.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#416 config(tics): set tide context to required
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#417 config: use github permission for ti-community-infra org
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#418 build: bump ti plugins version to v1.8.1
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/config/external_plugins_config.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#419 config: use teams instead of sig
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/L
