Repository ti-community-infra/configs, pull requests merged in 2021-06, with the labels that each got.

#335 config: remove lgtm term in cherry_pick_unapproved
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#336 build: bump all components version from v20210514-64850e516d to v20210521-0713522bd8
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#337 chore: cleanup unused configs
  ti-community-bots/dev/.gitignore
  ti-community-bots/dev/Makefile
  ti-community-bots/dev/cluster/bots_namespace.yaml
  ti-community-bots/dev/cluster/ing_ingress.yaml
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
  ti-community-bots/dev/cluster/ti_sync_bot_service.yaml
  ti-community-bots/dev/example/database_config.example.yaml
  ti-community-bots/dev/example/ti_sync_bot_config.example.yaml
Labels: size/L, status/LGT1, status/can-merge

#338 config: remove chaos from required checks for tidb-operator
  prow/config/config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge

#339 fix: revert tars from v1.5.13 to v1.5.12
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/XS, status/LGT1, status/can-merge

#341 config: rename test-live to test-prod
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#340 chore: cleanup ti-sync-bot configs
  prow/cluster/label_sync.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/L, status/LGT1, status/can-merge

#342 config: unrequired the github action test of ticdc
  prow/config/config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge

#343 config: add skip-unknown-contexts for tidb-operator
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#344 build: bump all ti plugins from v1.5.13 to v1.5.14
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#345 config: add release 5.1 config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, status/LGT1, status/can-merge

#347 config: do not protect ti-community-infra master branch
  prow/config/config.yaml
Labels: size/XS

#348 build(bump): bump ti plugins version from v1.5.14 to v1.5.15
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#349 config: add needs-cherry-pick-5.1 label for tikv and tidb repo
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#350 fix: refine ti-community-bot branch protection
  prow/config/config.yaml
Labels: size/S

#352 chore: Do not assign deployment requests to me
  .github/ISSUE_TEMPLATE/deploy-request.md
Labels: size/XS, status/LGT1, status/can-merge

#353 config: invite mini-bot into org
  orgs/ti-community-infra/bots-test/teams.yaml
  orgs/ti-community-infra/org.yaml
  scripts/peribolos.sh
Labels: size/XS, status/LGT1, status/can-merge

#355 config: remove integration test contexts check
  prow/config/config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/S, status/LGT1, status/can-merge

#354 chore: cleanup rustin-bot
  orgs/ti-community-infra/bots-test/teams.yaml
  orgs/ti-community-infra/org.yaml
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#356 build(bump): bump all ti plugins version from v1.5.15 to v1.6.0
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#357 config: make me inactive in blunderbuss
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#359 config: tide supports more ways to merge
  prow/config/config.yaml
Labels: size/XS

#360 config: add test-prod config for sig-community-infra
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/XS, status/LGT1, status/can-merge

#358 config: make pd and tikv use github permission
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#351 config: add the bot configuration for v5.1 branch in two doc repos
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
Labels: contribution, ok-to-test, size/M, status/LGT1, status/can-merge

#362 config: add checks for 1.1
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#361 config: enable tichi for pingcap/tidb-binlog
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/L, status/LGT1, status/can-merge

#363 config(tikv): remove required contexts on integration tests
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#364 config(pd): remove required contexts on integration tests
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#365 config(tikv): remove context integration-common-test,add context build
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge
