Repository ti-community-infra/configs, pull requests merged in 2021-07, with the labels that each got.

#367 config(ticdc): copy all the labels for ticdc
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#368 config: Revert "config: auto respond to lgtm (#334)"
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, size/L, status/LGT1, status/can-merge

#370 config: update config for tidb-operator release-1.2
  prow/config/config.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#371 config: require branchs up-to-date and enable tars plugin for br
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#372 feat: support generate labels.md
  .github/config.yml
  prow/.gitignore
  prow/config/labels.md
  prow/config/labels.md.tmpl
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  scripts/update-labels.sh
  scripts/verify-labels.sh
Labels: size/XXL

#373 config(ticdc): add ticdc labels
  go.sum
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Labels: sig/community-infra, sig/migrate, size/XXL, status/LGT1, status/can-merge

#374 config: update lgtm count for tidb-operator release-1.2
  prow/config/external_plugins_config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#376 ci: update the label_sync job
  prow/cluster/label_sync.yaml
Labels: size/XS

#377 config: add one type label in two doc repos
  prow/config/labels.md
  prow/config/labels.yaml
Labels: contribution, first-time-contributor, ok-to-test, sig/community-infra, sig/docs, size/M, status/LGT1, status/can-merge

#378 build(bump): bump all ti plugins version from v1.6.0 to v1.7.0
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#379 config: enable tichi for pingcap/parser
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/sql-infra, size/L, status/LGT1, status/can-merge

#380 fix: fix the lifecycle commenter query parameter
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/S, status/LGT1, status/can-merge

#381 config: remove some plugins in parser
  prow/config/plugins.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge

#382 build: bump all components version from v20210521-0713522bd8 to v20210701-3efe91b8cd
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#383 config: add release note plugin for tidb
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge

#384 build: bump ti plugin version to v1.7.1
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#385 config: enable release-note plugin for ticdc
  prow/config/config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/M, status/LGT1, status/can-merge

#386 config: add the bot configuration for v1.2 branch in the TiDB Operator Docs repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: contribution, ok-to-test, size/M, status/LGT1, status/can-merge
