Repository ti-community-infra/configs, pull requests merged in 2021-02, with the labels that each got.

#122 config: enable tichi for ti-community-infra/ti-sync-bot
  .prow.yaml
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/L, status/LGT1, status/can-merge

#124 config: enable label blocker to tikv
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#125 ci: add pull-configs-validate-orgs job
  .prow.yaml
Labels: size/M, status/LGT1, status/can-merge

#126 config: add ti-sync-bot config
  ti-community-bots/dev/.gitignore
  ti-community-bots/dev/Makefile
  ti-community-bots/dev/cluster/bots_namespace.yaml
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
  ti-community-bots/dev/cluster/ti_sync_bot_service.yaml
  ti-community-bots/dev/example/database_config.example.yaml
  ti-community-bots/dev/example/ti_sync_bot_config.example.yaml
Labels: size/L, status/LGT1

#127 chore: refine README.md
  README.md
Labels: size/XS

#128 ci: move jobs into prow jobs directory
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Labels: size/L

#129 config: add ok-to-test related labels
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/XL

#130 config: remove useless new line
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M

#132 fix: refine jobs
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M

#133 config: bump ti-sync-bot version v1.0.4
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
Labels: size/XS, status/LGT1, status/can-merge

#134 config: add ingress
  ti-community-bots/dev/cluster/ing_ingress.yaml
Labels: size/S, status/LGT1, status/can-merge

#135 config: add tls to ingress
  ti-community-bots/dev/cluster/ing_ingress.yaml
Labels: size/XS, status/LGT1, status/can-merge

#136 config: disable tars for configs
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/XS

#137 build: bump all plugins version
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Labels: size/M

#138 config: remove "Sig Info File Format" requirement for community repos
  prow/config/config.yaml
Labels: size/XS

#139 build: bump ti plugins version
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
Labels: size/S

#140 config: enable owners for community repos
  prow/config/external_plugins_config.yaml
Labels: size/S, status/LGT1, status/can-merge

#141 config: bump ti-sync-bot version to v1.1.0
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
  ti-community-bots/dev/example/ti_sync_bot_config.example.yaml
Labels: size/XS, status/LGT1, status/can-merge

#142 config: remove reprotest(1.14/1.15) from tiup required tasks
  prow/config/config.yaml
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#143 config: bump ti-sync-bot version to v1.1.1
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
Labels: size/XS, status/LGT1, status/can-merge

#144 config: enable tichi for rfcs
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#145 config: enable label for rfcs
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/M

#146 build: bump ti plugins version and enable validate config job
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#148 config: enable tichi for tidb
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XL, status/LGT1, status/can-merge

#149 config: fix broken link
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#150 build: bump ti-sync-bot version to v1.1.2
  ti-community-bots/dev/cluster/ti_sync_bot_deployment.yaml
Labels: size/XS, status/LGT1, status/can-merge

#152 feat: tiup: update reprotest task
  prow/config/config.yaml
Labels: ok-to-test, sig/tiup, size/XS, status/LGT1, status/can-merge

#153 config: modify commit message template for ti-community-infra
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#154 config: polish message
  prow/config/external_plugins_config.yaml
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#156 config: set empty commit body for tidb
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#155 config: add codecov
  prow/.gitignore
  prow/Makefile
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#157 fix: refine tidb commit body
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#158 fix: enable enforce_admins for tikv/tidb-operator
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#159 build: bump all commponents and plugins version
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#160 config: remove tidb's e2e CI requirement
  prow/config/config.yaml
Labels: size/XS
