Repository ti-community-infra/configs, pull requests merged in 2021-03, with the labels that each got.

#161 config: fix label blocker issue
  prow/config/external_plugins_config.yaml
Labels: size/XS

#162 config: tikv and tidb unfreeze release-4.0 code
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#163 build: bump all tichi plugins version from v1.3.0 to v1.3.3
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#164 config: send push events to tars
  prow/config/plugins.yaml
Labels: size/XS

#165 config: clarify tidb-operator commit message
  prow/config/config.yaml
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#166 build: bump all tichi plugins version from v1.3.3 to v1.3.5
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#167 fix: downgrade tars to version 1.3.3
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/XS

#168 build: bump all tichi plugins to v1.3.6
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/config/external_plugins_config.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#169 build: bump tars version from v1.3.3 to v1.3.6
  prow/cluster/ti_community_tars_deployment.yaml
  prow/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#170 config: uniform commit message format for tikv and pingcap
  prow/config/config.yaml
Labels: sig/community-infra, sig/diagnosis, sig/engine, sig/raft, sig/transaction, size/XS, status/LGT1, status/can-merge

#171 build: bump all tichi plugins version from v1.3.6 to v1.3.7
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#172 config: remove /merge autoresponder for tidb
  prow/config/external_plugins_config.yaml
Labels: size/S

#174 config: stop close ti-community-infra issues
  prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#175 config: update tichi milestone
  prow/config/plugins.yaml
Labels: size/XS

#176 feat: tiup: not marking required checks but wait for all to success
  prow/config/config.yaml
Labels: ok-to-test, size/S, status/LGT1, status/can-merge

#177 config: replace lightning-test with br-test in pd
  prow/config/config.yaml
Labels: ok-to-test, sig/community-infra, sig/scheduling, size/XS, status/LGT1, status/can-merge

#179 config: add branch-protection and context_options to the release branch of PD
  prow/config/config.yaml
Labels: ok-to-test, sig/scheduling, size/M, status/LGT1, status/can-merge

#178 config: enable tichi for docs / docs-cn / docs-dm / docs-tidb-operator
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/XL, status/LGT1, status/can-merge

#180 config: use the union method config for PD
  prow/config/config.yaml
Labels: ok-to-test, sig/community-infra, sig/scheduling, size/M, status/LGT1, status/can-merge

#181 config: change docs repo default require lgtm to 2
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/docs, size/XS, status/LGT1, status/can-merge

#182 config: fix tidb merge method
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#183 config: freeze release-4.0 for tidb/tikv and cleanup the docs repositories query
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#184 fix: set default sig for docs repositories
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/docs, size/XS, status/LGT1, status/can-merge

#186 fix: fix the require status check for pingcap/docs-dm and pingcap/docs-tidb-operator
  prow/config/config.yaml
Labels: sig/community-infra, sig/docs, size/S, status/LGT1, status/can-merge

#187 config: cancel freeze release-4.0 for tidb/tikv
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#188 config: enable lifecycle and require-matching-label ignore PR with -cherry-pick label for docs repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/S, status/LGT1, status/can-merge

#189 config: add branch-protection and context_options to the release-5.0 branch of PD
  prow/config/config.yaml
Labels: ok-to-test, sig/community-infra, sig/scheduling, size/S, status/LGT1, status/can-merge

#190 config: add release 5.0 config for tidb/tikv/pd repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/scheduling, size/M, status/LGT1, status/can-merge

#191 config: cancel freeze release-4.0 for tidb/tikv
  prow/config/config.yaml
Labels: size/S

#193 fix: refine typo
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#194 config: enable contribution for ti-community-infra
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#196 config: enable autobump for tichi
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#195 config: enable contribution for tikv
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/transaction, size/XS, status/LGT1, status/can-merge

#197 fix: fix the job config path option of autobump
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/XS, status/LGT1, status/can-merge

#198 config: add some labels
  prow/config/labels.yaml
Labels: size/L

#199 fix: refine label color
  prow/config/labels.yaml
Labels: size/L

#200 fix: refine label color
  prow/config/labels.yaml
Labels: size/XS

#201 config: enable tichi for dumpling
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/M, status/LGT1, status/can-merge

#203 config: add inactive reviewer for dumpling
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/S, status/LGT1, status/can-merge

#204 config: enable tichi for dm
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/L, status/LGT1, status/can-merge

#205 config: enable tichi for tidb-tools
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/L, status/LGT1, status/can-merge

#207 config: enable tichi for ticdc
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/L, status/LGT1, status/can-merge

#206 build: deploy cherrypicker
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/cherrypicker_service.yaml
Labels: size/M, status/LGT1, status/can-merge

#209 config: enable cherrypicker for dumpling
  prow/config/plugins.yaml
Labels: size/XS

#208 config: enable tichi for br
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/L, status/LGT1, status/can-merge

#211 config: add more required CI for dm
  prow/config/config.yaml
Labels: sig/migrate, size/XS, status/LGT1, status/can-merge

#212 config: refine required CI name of dm
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#210 chore: update labels in 4 docs repos
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, sig/community-infra, sig/docs, size/S, status/LGT1, status/can-merge

#213 ci: add ti-community-bot jobs
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#214 config: enable trigger for ti-community-bot
  prow/config/plugins.yaml
Labels: size/XS

#216 config: fix tidb-tools protection
  prow/config/config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#215 config: add codecov for ti-community-bot
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#218 ci: fix ti-community-bot codecov issue
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/XS

#217 config: refine migrate SIG repos branch protections
  prow/config/config.yaml
Labels: size/L, status/LGT1, status/can-merge

#219 config: refine codecov for ti-community-bot
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/XS

#220 config: use node codecov for ti-community-bot
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/XS

#221 config: correct tichi and ti-community-bot branch protection
  prow/config/config.yaml
Labels: size/S

#222 config: add notice to pd context_options
  prow/config/config.yaml
Labels: sig/community-infra, sig/scheduling, size/XS, status/LGT1, status/can-merge

#223 config: disable tars for ti-community-bot and clenup some configs
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#224 config: cleanup tikv/tidb context_options
  prow/config/config.yaml
Labels: size/L, status/LGT1, status/can-merge

#225 config: add restrictions to tikv and tidb release branchs
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#226 config: Modify pingcap/ticdc tars message to support triggering all tests
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#227 config: Freeze code for tidb/tikv 5.0
  prow/config/config.yaml
Labels: size/XS

#228 config: Freeze code for dumpling/tidb-tools/ticdc/br/pd 5.0
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M

#229 config: enable tichi for chaos-mesh/chaos-mesh
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, status/LGT1, status/can-merge

#230 config: enable tichi for devstats-dev-guide and devstats
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/XL, status/LGT1, status/can-merge

#231 fix: refine typos
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/sig-community-infra/teams.yaml
Labels: size/XS, status/LGT1, status/can-merge

#232 config: remove some useless labels
  prow/config/labels.yaml
Labels: size/S
