Repository ti-community-infra/configs, pull requests merged in 2021-04, with the labels that each got.

#233 config: disable ti-community-autoresponder for tidb
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#234 config: enable retitle for tidb
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/sql-infra, size/XS, status/LGT1, status/can-merge

#235 config: enable retitle for docs sig repos
  prow/config/plugins.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge

#236 config: add sig prefix for docs sig repos
  prow/config/external_plugins_config.yaml
Labels: contribution, ok-to-test, size/XS, status/LGT1, status/can-merge

#237 config: make auto bump once a week
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/S, status/LGT1, status/can-merge

#239 config: enable trigger for devstats-dev-guide
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-postsubmits.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-presubmits.yaml
Labels: size/M

#240 config: fix typos
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-postsubmits.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-presubmits.yaml
Labels: size/XS

#242 build: downgrade needs-rebase version
  prow/cluster/needs-rebase_deployment.yaml
Labels: size/XS

#243 config: increase grace_period for docs SIG repos
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/docs, size/XS, status/LGT1, status/can-merge

#241 config: add labels for 4 docs repos
  prow/config/labels.yaml
Labels: contribution, ok-to-test, sig/community-infra, sig/docs, size/XXL, status/LGT1, status/can-merge

#244 ci: add label sync cron job
  prow/cluster/label_sync.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: do-not-merge/hold, size/M

#245 config: enable release-note and dco for tichi
  prow/config/plugins.yaml
Labels: size/XS

#246 config: add more labels for tichi
  prow/cluster/label_sync.yaml
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/M

#247 config: fmt labels.yaml
  prow/config/labels.yaml
Labels: size/XS

#248 config: add some labels for tichi query
  prow/config/config.yaml
Labels: size/S

#249 config: remove status/WIP label
  prow/config/labels.yaml
Labels: size/XS

#251 config: enable ti-community-label for ticdc
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/migrate, size/M, status/LGT1, status/can-merge

#252 config: make tide status required for tichi
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/lifecycle-periodics.yaml
Labels: size/M

#253 config: make tide status required for tidb/tikv
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#254 config: enable contribution for docs sig
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, size/S, status/LGT1, status/can-merge

#255 ci: add configs-periodics.yaml
  prow/jobs/ti-community-infra/configs/configs-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#256 config: set tars update period to 2h
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/XS, status/LGT1, status/can-merge

#257 config: stop send pull request event to tars
  prow/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#258 build: bump all ti plugins from v1.5.1 to v1.5.2
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S

#259 build: Revert "config: set tars update period to 2h (#256)"
  prow/cluster/ti_community_tars_deployment.yaml
Labels: size/XS

#261 ci: add retester for tidb
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#262 config: retester only for master
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
Labels: size/XS

#263 config: set tidb reterser updated to 1h
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
Labels: size/XS

#264 fix: refine typo of tidb retester comment
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
Labels: size/XS, status/LGT1, status/can-merge

#265 config: remove unrequired status of tidb/tikv/pd
  prow/config/config.yaml
Labels: size/S, status/LGT1, status/can-merge

#266 build: bump all ti plugins from v1.5.2 to v1.5.3
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S

#267 config: adjust the updated time to 25m for tidb retester
  prow/jobs/pingcap/tidb/tidb-bot-periodics.yaml
Labels: size/XS, status/LGT1, status/can-merge

#268 config: enable auto-cc for docs sig
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: contribution, ok-to-test, sig/community-infra, sig/docs, size/L, status/LGT1, status/can-merge

#269 config: add retester for tikv
  prow/jobs/tikv/tikv/tikv-bot-periodics.yaml
Labels: sig/community-infra, sig/transaction, size/M, status/LGT1, status/can-merge

#270 build: bump all ti plugins from v1.5.3 to v1.5.4
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#271 build: support auto redirect
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/ing_ingress.yaml
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
Labels: size/M, status/LGT1, status/can-merge

#272 config: make ti-community-bot not strict
  prow/config/config.yaml
Labels: size/XS

#273 build: bump all ti plugins from v1.5.4 to v1.5.8
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S

#274 config: set cherrypicker push conflicting PR for dumpling
  prow/config/external_plugins_config.yaml
Labels: sig/community-infra, sig/migrate, size/XS, status/LGT1, status/can-merge

#276 config: enable cherrypicker for pd
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: sig/community-infra, sig/scheduling, size/L, status/LGT1, status/can-merge

#277 config: update pd label configuration
  prow/config/external_plugins_config.yaml
Labels: size/S

#280 build: bump all ti plugins from v1.5.8 to v1.5.9
  prow/cluster/ti-community-cherrypicker_deployment.yaml
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S, status/LGT1, status/can-merge

#281 config: add qiancai for auto-cc of docs-tidb-operator
  prow/config/external_plugins_config.yaml
Labels: contribution, first-time-contributor, ok-to-test, size/XS, status/LGT1, status/can-merge
