Repository ti-community-infra/configs, pull requests merged in 2021-11, with the labels that each got.

#453 config: update required status for TiCDC
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#455 config: add new branch release-5.3
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/L, ok-to-test, contribution

#454 config(tikv,pd): enable required code owner review
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#456 config(ticdc): add new label for ticdc
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#457 config: enable cherrypicker for test-plan repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#458 config: set a branch of docs-appdev as protected
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#460 config: add found/* label for tidb/tikv/pd/tiflash/tics
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#459 config: limit grammar of the associate issue number
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#461 config(tics): add required status unit-test
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#462 config(tics): modify integragion-test label
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#463 config: set pull as required check in docs-cn and docs
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#466 config: set the lgtm no for merge in docs repos release-5.3 to 1
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#465 config: add chaos-mesh/chaosd
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/L, ok-to-test, contribution, first-time-contributor

#468 config: set ran-huang as default reviewer for docs-tidb-operator
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution
