Repository ti-community-infra/configs, pull requests merged in 2022-02, with the labels that each got.

#505 config: apply new tide template for tikv repos
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#521 config: add release-5.4 branch config for docs repos
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#523 fix: use lazy mode to match commit message block
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#522 config: add release-1.3 branch config for docs-tidb-operator repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#524 config: update the PD required_status_checks
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#525 config: rename pingcap/tiflash to pingcap/tiflash-scripts
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution, first-time-contributor

#526 config: update the PD required-contexts
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#527 fix(config): rename missing parts of tiflash-scripts
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#529 config: enable linked issue check for tics
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#532 chore: unify to documentation in chaos-mesh
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#533 config: add v6.0 label to docs repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#531 config: enable tichi for tispark
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/L

#534 fix: fix typo on the label plugin config
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#535 config: remove build check in tiSpark release branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#536 fix: remove the reviewApprovedRequired on release branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#537 config: auto respond /run-all-tests after tars merge base
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS
