Repository ti-community-infra/configs, pull requests merged in 2022-09, with the labels that each got.

#644 config(tiflow): remove required status check of leak-test in part of branches
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#646 prow: use new github actions as required status
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#645 chore(prow/cluster): add ingress to prow.prow.net
  prow/cluster/ing_ingress.yaml
Labels: size/M, status/LGT1, status/can-merge

#647 config(tiflow): make engine-integration-test required for tiflow
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#648 chore(prow/config): update domain name
  .github/ISSUE_TEMPLATE/deploy-request.md
  README.md
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.md.tmpl
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#649 fix typo `project => protect` in `feature/ddl-as-service branch`
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#658 feat: add config for new release v6.3
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#659 fix(config): color values with quotes to avoid `+Inf` invalid errors
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#650 feat: new branch for chaos mesh release-2.4
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#666 Config(cp): add versions to won't fix list
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#676 config(docs): add branch config for release-1.4
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#610 config(tidb): enable ti-community-cherrypicker on `pingcap/tidb` repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S
