Repository ti-community-infra/configs, pull requests merged in 2022-12, with the labels that each got.

#697 config: update comment template of tar plugin
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#698 config: add release-6.5 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/L

#699 config(docs): update include_reviewers for docs and docs-cn reop
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#708 Revert "config: update comment template of tar plugin" in tiflash repo
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S

#709 config(tichi): decide the required contexts by prow tide
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#712 chore(deps): bump ticommunityinfra/tide to v20221207-9225e3a153
  prow/cluster/tide_deployment.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test

#727 chore(test-prod): disable tars plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#732 feat(tidb): forward webhook event to product jenkins ci server
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#733 feat(prow/cluster): add jenkins-operator component
  prow/cluster/jenkins-operator-deployment.yaml
  prow/cluster/jenkins-operator-rbac.yaml
  prow/cluster/jenkins-operator-service.yaml
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/L

#734 feat(test-prod): enable in_repo_config in test_prod repo
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#735 Create test-prod-presubmits.yaml
  prow/jobs/ti-community-infra/test-prod/test-prod-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#736 Update test-prod-presubmits.yaml
  prow/jobs/ti-community-infra/test-prod/test-prod-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#737 feat(test-prod): enable trigger plugin on test-prod
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#740 fix(configs/prow): fix jenkins job fetching
  prow/cluster/jenkins-operator-deployment.yaml
Labels: status/LGT1, status/can-merge, size/XS

#741 feat(pingcap/tidb): add prow-jenkins jobs
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#738 fix(ti-community-format-checker): merge tidb ti-community-format-checker configs.
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#742 feat(pingcap/tidb): enable trigger plugin
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#743 fix(prow/cluster): disable report for jenkins-operator comonent
  prow/cluster/jenkins-operator-deployment.yaml
Labels: status/LGT1, status/can-merge, size/XS

#745 ci: bump checkconfig image
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#746 Revert "ci: bump checkconfig image"
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#747 Revert "Revert "ci: bump checkconfig image""
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#744 Feature/jenkins-operator-job-url-using-jenkins-url
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jenkins-operator-deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-periodics.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
  prow/jobs/ti-community-infra/tichi/tichi-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#748 chore(prow/jobs/pingcap/tidb): update wip jobs
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#749 chore(prow/jobs/pingcap/tidb): enable job `build`
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#750 chore(prow/jobs/pingcap/tidb): enable job `check`
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#751 chore(prow/jobs/pingcap/tidb): enable job `check2`, `mysql-test`, `unit-test`
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#752 chore(prow/jobs/tikv/pd): add wip presubmits jobs
  prow/config/plugins.yaml
  prow/jobs/tikv/pd/pd-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#753 chore(prow/jobs/tikv/pd): enable job `build`
  prow/jobs/tikv/pd/pd-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#754 chore(prow/jobs/pingcap/tidb): add jobs for branches release-6.[1-4]
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/L

#755 chore(prow/jobs/pingcap/tidb): enable postsubmits job `e2e-test`
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#756 Revert "chore(prow/jobs/pingcap/tidb): add jobs for branches release-6.[1-4]"
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S

#757 chore(prow/jobs/pingcap/tidb): add some postsubmit jobs
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
Labels: size/M, status/LGT1, status/can-merge
