Repository ti-community-infra/configs, pull requests merged in 2022-03, with the labels that each got.

#538 config: only allow release team to approve cherry-pick
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#539 config: change tics to lgt2
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#540 build: bump ti plugin to v2.0.3
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_format_checker_deployment.yaml
  prow/cluster/ti_community_issue_triage_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#541 config: change sig/ labels to area/ in docs repos
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XXL, ok-to-test, contribution

#542 config: fix a typo in label
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#543 config: rename tics to tiflash
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution

#544 config: add release-6.0
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/L, ok-to-test, contribution

#546 config: update the PD required-contexts for release-6.0
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#547 build: bump ti plugins to v2.0.4
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_format_checker_deployment.yaml
  prow/cluster/ti_community_issue_triage_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: size/S

#545 config: enforce CLA checking for tiflash
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#550 change checks for chaos-mesh on master branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution
