Repository ti-community-infra/configs, pull requests merged in 2022-06, with the labels that each got.

#569 Revert "config: set the docs-tiem branch of docs-cn as protected"
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#582 config(docs): add release 6.1 branch config for docs repos
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#583 chore: append xlgao-zju as chaos mesh committer
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#584 config(docs): add v6.2 label to docs repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#585 config: invite @wuhuizuo joining the infra team
  orgs/ti-community-infra/community-infra-committers/teams.yaml
  orgs/ti-community-infra/config-reviewers/teams.yaml
  orgs/ti-community-infra/org.yaml
Labels: status/LGT1, status/can-merge, size/XS

#586 config: enable tichi for `pingcap/tiunimanager` and `pingcap/tiunimanager-ui`
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/L, first-time-contributor

#587 config: remove parse repo ci check
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test

#589 *: remove real tikv
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#590 config: remove tomshawn from the auto reviewer of docs repo
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#592 config: update the status checks for the pingcap/docs repository
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#591 config: exclude Mini256 from the blunderbuss reviewers
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS
