Repository ti-community-infra/configs, pull requests merged in 2022-05, with the labels that each got.

#565 config: set the docs-tiem branch of docs-cn as protected
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#566 config: remove the Semantic Pull Request CI
  prow/config/config.yaml
Labels: size/S

#567 config: remove ti-challenge-bot repo config
  prow/cluster/label_sync.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/L

#568 config: Update config for TiDB Dashboard
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution, first-time-contributor

#570 config(ticdc): make tide required for tiflow
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#571 add required to realtikv-test on tidb
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#573 config: add release-6.1 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/L, ok-to-test, contribution

#574 config: add missing release-6.1 labels
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S

#575 config(tiflow): add area/engine label to tiflow repo
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#576 config: change the cherry_pick_unapproved regexp
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test

#572 config: join purelind as ti-community-infra reviewer
  orgs/ti-community-infra/community-infra-reviewers/teams.yaml
  orgs/ti-community-infra/config-reviewers/teams.yaml
  orgs/ti-community-infra/org.yaml
Labels: status/LGT1, status/can-merge, size/S

#577 config: update require context for tidb-dashboard
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#578 config: update config.yaml for chaos-mesh/chaosd
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#579 add arm64 test for Chaos Mesh
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#580 tiflash: support tiflash feature branch planner_refactory
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge
