Repository ti-community-infra/configs, pull requests merged in 2022-08, with the labels that each got.

#611 config(tidb): label sync for tidb
  prow/cluster/label_sync.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#612 tiflash: remove tiflash feature branch planner_refactory
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution, first-time-contributor

#617 chore(dep): enable k8s file auto updating
  .github/renovate.json5
  renovate.json
Labels: size/S

#635 prow/config: support tidb feature branch distribute-reorg
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution, first-time-contributor

#636 Config( triage ): Add "6.0" to "wontfix_verions" list.
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#637 config: check invalid title for tidb
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test, contribution, first-time-contributor

#638 configs: missed regexp for title
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#639 configs: delete check_title requirement
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#641 prow/config: support tidb feature branch ddl-as-service
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution, first-time-contributor

#642 build(prow/cluster): upgrade k8s manifests to k8s `v1.22`
  prow/cluster/crier_rbac.yaml
  prow/cluster/deck_rbac.yaml
  prow/cluster/hook_rbac.yaml
  prow/cluster/horologium_rbac.yaml
  prow/cluster/ing_ingress.yaml
  prow/cluster/prow_controller_manager_rbac.yaml
  prow/cluster/prowjob_customresourcedefinition.yaml
  prow/cluster/sinker_rbac.yaml
  prow/cluster/statusreconciler_rbac.yaml
  prow/cluster/tide_rbac.yaml
Labels: status/LGT1, status/can-merge, size/L

#643 prow/config: update wontfix verion for tidb/tikv
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution
