Repository ti-community-infra/configs, pull requests merged in 2022-07, with the labels that each got.

#593 config(tikv/tikv): auto apply to milestone for new pull request
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S

#594 config: add shichun-0415 as the auto reviewer of docs-cn
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#595 config(ti-community-infra): add @wuhuizuo and his bots to teams
  orgs/ti-community-infra/bots-test/teams.yaml
  orgs/ti-community-infra/community-infra-reviewers/teams.yaml
  orgs/ti-community-infra/maintainers/teams.yaml
  orgs/ti-community-infra/org.yaml
Labels: status/LGT1, status/can-merge, size/S

#596 config(tiflow): support feature branch check
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge, ok-to-test

#598 config(pingcap/tiflash): enable comment to set merge method for tiflash
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#600 config: add `tide/merge-method-*` pr labels
  prow/config/labels.md
  prow/config/labels.yaml
  scripts/update-labels.sh
Labels: size/M, status/LGT1, status/can-merge

#602 config: update job's cli args
  prow/cluster/label_sync.yaml
  prow/config/labels.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#604 config: add repo `pingcap/tiflash` into labels sync list
  prow/cluster/label_sync.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#605 Feature/protect for hotfix branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#607 chore: new branch release-2.3 for chaos mesh
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, needs-ok-to-test, contribution

#608 config: add `tide/merge-method-merge` label to tiflash repo
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS

#609 fix: modify chaos-mesh release-2.3 required status check
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution
