Repository ti-community-infra/configs, pull requests merged in 2022-04, with the labels that each got.

#551 config: add CLA & license checking for tiflash
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#552 config: trust affects label for tikv and pd repos
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S

#553 config: add release 6.0 branch config for docs repo
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#554 chore: apply gha e2e test on release-2.1
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#555 config: fix docs-cn jenkins ci name
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#556 config: add tiflash teams for owners config
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#557 config(docs): add v6.1 label to docs repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#558 config: enable issue triage check for tikv and pd
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S

#560 config: remove unnecessary tikv release build
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#561 config(tiflash): set tiflash ut as required status for release branch
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#563 config(tiflow): add found label for tiflow repo
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#564 chore: new branch release-2.2 for chaos mesh
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution
