Repository ti-community-infra/configs, pull requests merged in 2022-10, with the labels that each got.

#679 config(tidb): update needs cherry pick labels
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge

#680 config(tidb): rename needs cherry pick labels
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, status/LGT1, status/can-merge

#683 refactor(tikv): update `need_cherry_pick_label_prefix` for tikv
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#684 chore(tikv/tikv): update `additional_labels` for plugin `ti-community-label`
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S

#685 config: remove shichun-0415 as the auto reviewer of docs-cn
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#682 chore(scripts): optimize update-labels.sh to avoid clone repo multi times
  scripts/update-labels.sh
Labels: status/LGT1, status/can-merge, size/S

#681 Add 6.3 to wonfix_versions in tikv repo.
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#688 fix(tikv/tikv): enable plugin ti-community-cherrypicker
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#689 prow/config: support tidb feature branch reorganize-partition
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution, first-time-contributor

#687 feat(chaos-mesh/chaos-mesh): enable cherry-picker plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge
