Repository ti-community-infra/configs, pull requests merged in 2022-11, with the labels that each got.

#686 *: clean `previously` fields for renamed labels
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, status/LGT1, status/can-merge

#690 config: add release-6.4 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/L

#692 config(pingcap/tidb): forward `pull_request` github event to staging jenkins CI
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#691 feat: update prow config for chaos-mesh with new branch release-2.5
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S, ok-to-test, contribution

#694 Config(triage): Add 6.3 and 6.3 to won'tfix version list
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#696 config(pingcap/tidb): add label for sqlancer
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution
