Repository ti-community-infra/configs, pull requests merged in 2022-01, with the labels that each got.

#501 build: bump tide version to v20211228-v1.0.2
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#502 revert: Revert "config: don't add the do-not-merge label temporarily (#499)"
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/S

#503 config: add component/owner label to tiflow repo
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#504 chore: update chaos-mesh config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge, needs-ok-to-test, contribution, first-time-contributor

#506 config: update tidb-operator config
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#507 config: fix tidb-operator config
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#509 config(pd): fix pd required contexts
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#510 config: update required_status_checks for tidb-operator
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution

#512 build: bump prow version to v20211229-5ea9b96f66 and custom tide version to v1.0.3
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/org/bot-periodics.yaml
Labels: size/M, status/LGT1, status/can-merge

#513 config: enable issue triage on test-prod
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#514 build: bump ti plugin version from v2.0.0 to v2.0.1
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_format_checker_deployment.yaml
  prow/cluster/ti_community_issue_triage_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#515 config: add format-checker skip label for tidb repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/XS

#516 config: enable issue triage check for tidb, tiflow
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#517 config: remove not maintained versions for tidb
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS, ok-to-test, contribution, first-time-contributor

#518 config: fix the config and remove the start time
  prow/config/external_plugins_config.yaml
Labels: size/XS

#519 build: bump ti plugin from v2.0.1 to v2.0.2
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_format_checker_deployment.yaml
  prow/cluster/ti_community_issue_triage_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#520 build: bump tide version to v20220130-v1.0.4
  prow/cluster/tide_deployment.yaml
Labels: status/LGT1, status/can-merge, size/XS
