Repository ti-community-infra/configs, pull requests merged in 2023-03, with the labels that each got.

#812 chore(prow/config): delete prow job contexts in branch protection for tidb@master
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#813 Revert "chore(prow/config): delete prow job contexts in branch protection for tidb@master"
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#815 feature(prow/config): enable cherry-pick plugin on `tikv/client-java` repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#816 chore(prow/config): add repo pingcap-qe/benchbot
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#817 config: add release-7.0 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#818 fix(prow/jobs/ti-community-infra/test-infra): fix prow jobs
  prow/jobs/ti-community-infra/test-infra/test-infra-postsubmits.yaml
  prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
Labels: size/M, lgtm, approved

#819 fix(prow/jobs/ti-community-infra/test-infra): fix prow jobs
  prow/jobs/ti-community-infra/test-infra/test-infra-postsubmits.yaml
  prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
Labels: size/S, lgtm, approved

#820 config: add trigger plugin to tiflow
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#822 chore(prow/config): add repo pingcap-qe/test-plan
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#825 chore(prow/config): add repos in pingcap-qe
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#823 config(docs): remove auto cc
  prow/config/external_plugins_config.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#821 config: add owners plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#827 config(tiflow): remove some it required label
  prow/config/config.yaml
Labels: size/XS, lgtm, approved
