Repository ti-community-infra/configs, pull requests merged in 2023-09, with the labels that each got.

#952 replace TiProxy with tiproxy
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, ok-to-test, contribution, first-time-contributor, lgtm, approved

#953 feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, lgtm, approved

#954 Revert "feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks"
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, lgtm, approved

#955 Revert "Revert "feat(pingcap/tidb): block mergeing for pull requests which have none finished test tasks""
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, lgtm, approved

#956 chore(prow/config): enable pr format checker plugon on test-prod repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#957 chore(prow/config): enable pr format checker plugon on test-prod repo master branch
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#958 chore(prow/config): fix pr format checker plugon on test-prod repo master branch
  prow/config/external_plugins_config.yaml
Labels: size/S, lgtm, approved

#959 fix(pingcap/tidb): pr format checker regex string
  prow/config/external_plugins_config.yaml
Labels: size/S, lgtm, approved

#960 fix(pingcap-qe/tidb-test): rename `pingcap/tidb-test` to `PingCAP-QE/tidb-test`
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#963 Add sig prefix for tidb repo to support sig/xxx label
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved

#964 config: support lable ok-to-test on test-prod
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#965 config: support lable ok-to-test on tidb & tidb-operator
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#966 config: support lable ok-to-test on tiflow & tiflash
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#967 config: support add & remove label needs-ok-to-test on tidb-operator
  prow/config/external_plugins_config.yaml
Labels: size/S, lgtm, approved

#962 fix(pingcap-qe/tidb-test): add service for `pingcap-inc/enterprise-plugin` repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#968 config: add release-7.4 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#969 config: remove dmr version config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, lgtm, approved
