Repository ti-community-infra/configs, pull requests merged in 2023-01, with the labels that each got.

#758 chore(prow/jobs/pingcap/tidb): add two merged-tests to postsubmits
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/S

#759 chore(prow/jobs/pingcap/tidb): enable context report for postsubmit jobs
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#760 fix(prow/config): add `release-6.5` to triage list
  prow/config/external_plugins_config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#761 ci(ti-community-infra/test-infra): add jobs
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/test-infra/test-infra-postsubmits.yaml
  prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/L

#763 fix(prow/jobs/pingcap/tidb): fix trigger branches for hotfix branches
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
Labels: size/M, status/LGT1, status/can-merge

#764 chore(prow/config): enable external plugin ti-*-cherry-pick on `pingcap/tidb-operator` repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#768 chore(pingcap/tidb): disable status report for unstable mergedci
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#769 ci(ti-community/test-infra): fix lint jobs
  prow/jobs/ti-community-infra/test-infra/test-infra-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#770 fix(prow/config): prefer to using in-cluster external dns
  prow/config/external_plugins_config.yaml
Labels: size/M

#771 Revert "fix(prow/config): prefer to using in-cluster external dns"
  prow/config/external_plugins_config.yaml
Labels: size/M

#772 fix(prow/cluster): bump tide images to support `replace` in template
  prow/cluster/jenkins-operator-deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, status/LGT1, status/can-merge

#773 fix(prow/cluster, prow/config): bump tide images and fix tide merge template
  prow/cluster/tide_deployment.yaml
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#774 fix(prow/config): fix tide merge templates
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#778 fix(prow/config): add hotfix branche prefix to execlude branches for tide query
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#781 fix(prow/cluster): bump ti-community plugins with cherry pick invite fixing
  prow/cluster/ti_community_autoresponder_deployment.yaml
  prow/cluster/ti_community_blunderbuss_deployment.yaml
  prow/cluster/ti_community_cherrypicker_deployment.yaml
  prow/cluster/ti_community_contribution_deployment.yaml
  prow/cluster/ti_community_format_checker_deployment.yaml
  prow/cluster/ti_community_issue_triage_deployment.yaml
  prow/cluster/ti_community_label_blocker_deployment.yaml
  prow/cluster/ti_community_label_deployment.yaml
  prow/cluster/ti_community_lgtm_deployment.yaml
  prow/cluster/ti_community_merge_deployment.yaml
  prow/cluster/ti_community_owners_deployment.yaml
  prow/cluster/ti_community_tars_deployment.yaml
  prow/cluster/tichi_web_deployment.yaml
Labels: status/LGT1, status/can-merge, size/S

#782 chore(prow/config): test new merge template for repos in ti-community-infra org
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#783 fix(prow/config): update merge template for pingcap/tidb repo
  prow/config/config.yaml
  prow/jobs/ti-community-infra/test-prod/test-prod-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XS

#784 chore(prow/cluster): offline domain prow.tidb.io
  prow/cluster/ing_ingress.yaml
Labels: size/M, status/LGT1, status/can-merge

#786 chore(pingcap/tidb): remove tidb required check
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#787 chore(pingcap/tiflash): remove tiflash required context `check-license` in branch protect rules
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#788 feat(prow/jobs): delete jobs for pingcap and tikv org
  prow/config/config.yaml
  prow/config/plugins.yaml
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
  prow/jobs/tikv/pd/pd-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#789 Revert "feat(prow/jobs): delete jobs for pingcap and tikv org"
  prow/config/config.yaml
  prow/config/plugins.yaml
  prow/jobs/pingcap/tidb/tidb-postsubmits.yaml
  prow/jobs/pingcap/tidb/tidb-presubmits.yaml
  prow/jobs/tikv/pd/pd-presubmits.yaml
Labels: status/LGT1, status/can-merge, size/XXL

#790 Feature/add-ci-repo
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/L

#791 feat(prow/config): add config update file map for pingcap-qe/ci repo
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS
