Repository ti-community-infra/configs, pull requests merged in 2023-11, with the labels that each got.

#987 chore(prow/config): add event router to tekton cd for for tikv org
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#989 Support `pingcap/monitoring` repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#991 Add tirelease webhook of tikv/tikv
  prow/config/plugins.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#992 Revert "Add tirelease webhook of tikv/tikv"
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#993 Update plugins.yaml
  prow/config/plugins.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#994 chore(pingcap/community): disable auto merge by bot
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#997 Change configuration: EOS of TiDB v5.3
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved
