Repository ti-community-infra/configs, pull requests merged in 2023-07, with the labels that each got.

#924 config(prow/config): forbid merge pull request to release-x.y.z of `tidb-test` repo
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#926 config(prow/config): exclude `cherry-pick-approved` label when create cherry-pick pull requests
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#927 config(prow/config): add rerun auth configs
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#928 config(prow/config): update branch protection config for `pingcap/tidb` release branches
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#930 config(prow/config): fix team slug for deck rerun auth configs
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#931 Revert "config(prow/config): update branch protection config for `pingcap/tidb` release branches"
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#932 label: remove the v6.6 cherry-pick labels for docs-cn and docs
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#934 config(prow/config): update branch protection config for pingcap/tidb release-6.1
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#936 config(tiproxy): add repo pingcap/tiproxy config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#937 config(tiproxy): repo names are case-sensitive.
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#935 config(prow/config): update branch protection config for pingcap/tidb release-6.5
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#933 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#938 config(prow/config): update branch protection config for `pingcap/tidb` release branches
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#939 config(prow/config,prow/jobs): offline support to repo ti-community-infra/ti-community-bot
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-postsubmits.yaml
  prow/jobs/ti-community-infra/ti-community-bot/ti-community-bot-presubmits.yaml
Labels: size/L, lgtm, approved

#940 config(pingcap-qe/artifacts): forward events to tekton event listenser
  prow/config/openai/tasks.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#942 config(prow/config): migrate to new plugins configuration struct
  prow/config/openai/tasks.yaml
  prow/config/plugins.yaml
Labels: size/XXL, lgtm, approved

#943 fix(pingcap-qe/artifacts): fix tekton external plugin
  prow/config/plugins.yaml
Labels: lgtm, approved
