Repository ti-community-infra/configs, pull requests merged in 2023-08, with the labels that each got.

#944 config: add release-7.3 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#946 Revert "chore(pingcap/tidb): disable github review approve and codeowner required options"
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#948 chore(pingcap/*docs*): no automatic review on pull request which has `lgtm` labeled
  prow/config/openai/tasks.yaml
Labels: size/XS, lgtm, approved

#949 fix(pingcap/community): disable cherry pick external plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#947 label: remove the v7.0 cherry-pick labels for docs-cn and docs
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#950 chore(pingcap/tiup): update approve plugin config
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#951 chore: update prow config since EOS of v5.2
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved
