Repository ti-community-infra/configs, pull requests merged in 2023-10, with the labels that each got.

#970 fix(prow/config): fix comment template of `cherry_pick_unapproved` plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#972 chore(prow/config): remove dmr version config v7.4
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, lgtm, approved

#973 fix(pingcap/tidb): fix tide merge commit message template
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#971 config(tidb): prioritize the PRs with `Priority/P*` labels in merging queue
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#974 chore(prow/config): vip for a pr in pingcap/tidb
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#975 Revert "chore(prow/config): vip for a pr in pingcap/tidb"
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#977 config: add release-7.5 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#980 chore(prow/config): add event router to tekton cd for for pingcap org
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#983 chore(prow/config): vip for a pr in pingcap/tidb
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#984 Revert "chore(prow/config): vip for a pr in pingcap/tidb"
  prow/config/config.yaml
Labels: size/M, lgtm, approved
