Repository ti-community-infra/configs, pull requests merged in 2023-04, with the labels that each got.

#829 fix(prow/config): fix cherry-pick config for pingcap-qe/test-plan
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#830 fix(prow/config): fix cherry-pick config for pingcap-qe/test-plan
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#831 chore(prow/config): switch review plugins to lgtm + approve for repos in `ti-community-infra`
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#832 chore(orgs/ti-community-infra): delete teams sync configs for archived repos
  go.mod
  go.sum
  prow/cluster/label_sync.yaml
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/jobs/ti-community-infra/configs/configs-postsubmits.yaml
  prow/jobs/ti-community-infra/configs/configs-presubmits.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-postsubmits.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-presubmits.yaml
  scripts/peribolos.sh
Labels: size/XXL, lgtm, approved

#833 label: remove the needs-cherry-pick labels for archived doc versions
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, ok-to-test, contribution, lgtm, approved

#835 chore: update renovate config
  .github/renovate.json
  .github/renovate.json5
Labels: size/S, lgtm, approved

#836 Revert "chore: update renovate config"
  .github/renovate.json
  .github/renovate.json5
Labels: size/S, lgtm, approved

#828 chore(prow/config): delete configs for release-4.0 and release-5.0
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, lgtm, approved

#837 fix(prow/config): fix failure of branch protection cron job
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XL, lgtm, approved

#840 config(docs): add docs tidb operator release-1.5
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#841 chore(prow/config): dispatch push event to jenkins-gitee for pingcap-qe/ci repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#842 chore(prow/config): delete useless labels and remove v4.0 and v5.0 from maintain versions
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, lgtm, approved

#838 feat(prow/cluster): update prow deployment to new image
  prow/cluster/branchprotector.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/jenkins-operator-deployment.yaml
  prow/cluster/label_sync.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-postsubmits.yaml
  prow/jobs/ti-community-infra/devstats-dev-guide/devstats-dev-guide-presubmits.yaml
Labels: size/M, lgtm, approved

#843 config(pingcap/tidb-test): enable cherry pick plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#845 deps(prow/cluster): bump hook image to v20230418-8438f51444
  prow/cluster/hook_deployment.yaml
Labels: size/XS, lgtm, approved

#846 deps(prow/cluster): bump hook image to v20230324-18d2952
  prow/cluster/hook_deployment.yaml
Labels: size/XS, lgtm, approved

#847 config: add release-7.1 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#844 feat(prow): kustomize config and jobs
  prow/config/kustomization.yaml
  prow/jobs/kustomization.yaml
  prow/kustomization.yaml
Labels: size/M, lgtm, approved

#848 fix(prow/config): fix kustomization file
  prow/config/kustomization.yaml
Labels: size/XS, approved

#849 revert(prow/config): restore tide merge templates
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#850 fix(prow/config): remove `config-updater` plugin on repos for GitOps
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#851 fix(prow/config): fix exscape in merge templates
  prow/config/config.yaml
Labels: lgtm, approved

#852 fix(prow/config): fix exscape in merge templates
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#853 fix(prow/config): update config for `pingcap/tiflow` about branch protection
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#856 chore(prow/config): move out `pingcap-qe/artifacts` to another bot
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#857 feat(prow/config): dispatch event to chatgpt external plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#858 feat(prow/config): dispatch event to chatgpt external plugin for `tikv/tikv` repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#859 Revert "feat(prow/config): dispatch event to chatgpt external plugin for `tikv/tikv` repo"
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved
