Repository ti-community-infra/configs, pull requests merged in 2023-02, with the labels that each got.

#793 Update config.yaml
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#765 chore(prow/config): do not watching migrated or archived repositories
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XL, status/LGT1, status/can-merge

#797 fix(prow/config): disable tars plugin on pingcap/tidb repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S

#796 config: add release-6.6 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, status/LGT1, status/can-merge

#795 feat(pingcap/tidb-test): enable trigger plugin for tidb-test
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#798 config: add missing label for release-6.5 and release-6.4
  prow/config/labels.md
  prow/config/labels.yaml
Labels: status/LGT1, status/can-merge, size/S

#799 config(pingcap/tiflash-scripts): tiflash-scripts remove build-ci
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#800 config: fix indent
  prow/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#803 config: add repo pingcap-qe/artifacts
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#801 feat: add tidb-test required status
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/XS

#805 config: add plugins to tidb-test
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/XS

#806 Revert "feat: add tidb-test required status"
  prow/config/config.yaml
Labels: size/XS

#807 feat(prow/config): enable auto prow labeling for pingcap-qe/* repo
  prow/config/plugins.yaml
Labels: status/LGT1, status/can-merge, size/S

#809 fix(prow/config): fix tide query config for repo `ti-community-infra/configs`
  prow/config/config.yaml
Labels: status/LGT1, status/can-merge, size/S

#808 feat: add prow owner files
  OWNERS
  OWNERS_ALIASES
  prow/OWNERS
  prow/cluster/OWNERS
  prow/config/OWNERS
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/jobs/OWNERS
  scripts/OWNERS
Labels: size/M, status/LGT1, lgtm, approved

#802 chore(prow/config): remove dmr versions from triage list
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#810 fix(prow/config): fix link urls for approve plugin
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/XL, lgtm, approved

#811 fix(prow/config): fix plugin list url for approve plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved
