Repository ti-community-infra/configs, pull requests merged in 2023-12, with the labels that each got.

#1000 Update config.yaml
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1001 Add a "MariaDB" label for tiflow repo
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#1002 Revert "Update plugins.yaml"
  prow/config/plugins.yaml
Labels: size/XS, needs-ok-to-test, contribution, lgtm, approved

#1004 fix(tikv/tikv,tikv/pd): enable merging on `feature/*` branches
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#1005 docs-cn/docs: add the "2024–tidb-docs-dash" label
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#1007 update the label name: 2024-tidb-docs-dash
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#1008 chore(pingcap/tiup): disable required for refresh branch
  prow/config/config.yaml
Labels: lgtm, approved

#1009 config: add plugins to pingcap/tidb-engine-ext
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1010 config: add plugins to tikv/migration
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1011 labels: add a new label affect-ticdc-config-docs for pingcap/tiflow
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved
