Repository ti-community-infra/configs, pull requests merged in 2023-06, with the labels that each got.

#868 config(prow/config): migrate review plugins to lgtm + approve for repos in `pingcap` ORG
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XXL, lgtm, approved

#877 config(prow/config): fix tide for release branches
  prow/config/config.yaml
Labels: size/S

#878 config(prow/config): disable `release-note` plugin for docs repos
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#879 config(prow/config): fix external plugin forwards for tidb-operator
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#880 config(prow/config): disable blunderbuss plugin and update approve config for docs repos
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#881 config(prow/config): fix approve config for docs repos
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#882 config(prow/config): delete forwarding to prow-ee.pingcap.net
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#884 config(prow/config): migrate tigger comment from `/merge` to `/approve` for tiflash repos
  prow/config/external_plugins_config.yaml
Labels: size/S, lgtm, approved

#886 config(prow/config): remove plugin blunderbuss for `pingcap/tiflash` repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#883 chore(prow/config): delete useless config fields
  prow/cluster/README.md
  prow/config/plugins.yaml
  prow/jobs/README.md
Labels: size/S, lgtm, approved

#887 config(prow/config): remove plugin blunderbuss for `pingcap/tiflow` repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#888 config(prow/config): remove plugin blunderbuss for `pingcap/tidb` repo
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#897 config(prow/config): update the tars required PR label from `approved` to `lgtm`
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#900 config(tiflow): update required status on tiflow release-5.3
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#903 config(tikv/pd): enable size plugin
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#904 config(prow/cronjobs): add branch protect and label sync jobs
  prow/config/kustomization.yaml
  prow/cronjobs/branch-protector.yaml
  prow/cronjobs/label-sync.yaml
Labels: size/L, lgtm, approved

#905 config(prow/config): add release-3.* and release-4.* into tide's query branches for docs repos
  prow/config/config.yaml
Labels: size/L, lgtm, approved

#906 config(prow/prow): execlude old review labels when create cherry-pick PR
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#907 config(prow/config): update external plugin configs
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#908 config(prow/config): enable chatgpt external plugins for docs repo
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#909 fix(prow/cronjobs): fix github app id env var
  prow/cronjobs/branch-protector.yaml
  prow/cronjobs/label-sync.yaml
Labels: size/S, lgtm, approved

#910 config(pingcap/tiflow): inherit `lgtm` label when create cherry-pick pull request
  prow/config/external_plugins_config.yaml
Labels: size/S, lgtm, approved

#911 config(prow/config): add LTS release branches in to tide include branches
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#912 config(pingcap/docs*): allow add `lgtm` label by document team on pull requests
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#913 prow/config: fix an id typo
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved

#898 config(tiflow): remove some required status on tiflow
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#901 config(tiflow): remove some required check because prow trigger
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#916 config: allow merging pr to release-1.x in docs-tidb-operator
  prow/config/config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#917 config: add release-7.2 branch config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#914 chore(prow/config): delete prow job contexts in branch protection for tidb@master
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#919 config(prow/config): reduce tide query interval from 120s to 90s
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#918 config: update the PD required-contexts
  prow/config/config.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved

#920 config(prow/config): add `ti-community-autoresponder` external plugin on `pingcap/*`
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#921 config: correct indentation
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#922 config(prow/config): deprecate bot congiuration for release-5.1 branches
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XL, lgtm, approved

#923 config(prow/config): migrate openai config from pingcap-qe/ee-ops repo
  prow/config/kustomization.yaml
  prow/config/openai/tasks.yaml
Labels: size/M, lgtm, approved
