Repository ti-community-infra/configs, pull requests merged in 2024-04, with the labels that each got.

#1040 config: add trigger plugin for tikv
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1041 config: add config for branch release-8.1
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1042 opt(prow/config): update to config to delete the released v8.0.0 DMR version
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XXL, lgtm, approved

#1034 feat(pingcap/kvproto): control reviewing approvals with prow OWNERS
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1043 config(tikv): update tikv ut required context
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1045 Revert "config(tikv): update tikv ut required context"
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1046 config(tikv): update tikv ut required context
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1044 config: remove tikv tide required context
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1047 Fix tasks.yaml
  prow/config/openai/tasks.yaml
Labels: size/S, lgtm, approved

#1049 config(pd): update the review list
  prow/config/external_plugins_config.yaml
Labels: size/XS, needs-ok-to-test, contribution, first-time-contributor, lgtm, approved

#1051 REQUEST: deploy chatgpt plugin for pingcap/tiflow
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1052 config(tiflash): update required contect on tiflash master
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1053 config(tiflash): remove two required context on master
  prow/config/config.yaml
Labels: size/XS, lgtm, approved
