Repository ti-community-infra/configs, pull requests merged in 2024-02, with the labels that each got.

#1022 config: set 'pull-verify' as required status on docs & docs-cn
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#1024 config: tidb-test add plugin lifecycle
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1025 fix(prow/config): fix the color value for label `2024-tidb-docs-dash`
  prow/config/labels.yaml
Labels: size/XS, lgtm, approved

#1026 chore(prow/config): split the cron job to serval containers
  prow/cronjobs/label-sync.yaml
Labels: size/L, lgtm, approved

#1027 fix(prow/config): fix the color value for label `2024-tidb-docs-dash`
  prow/config/labels.yaml
Labels: size/XS, lgtm, approved

#1028 Revert "chore(prow/config): split the cron job to serval containers"
  prow/cronjobs/label-sync.yaml
Labels: size/L, lgtm, approved

#1031 fix(pingcap/monitoring): fill the cherry-pick config
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#1033 chore(prow/config): simple configuration for `ti-community-issue-triage` plugin
  prow/config/external_plugins_config.yaml
Labels: lgtm, approved

#1035 chore(prow/config): fix the configuration on repo branches
  prow/config/config.yaml
  prow/config/openai/tasks.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved
