Repository ti-community-infra/configs, pull requests merged in 2024-09, with the labels that each got.

#1103 feat(tikv/rocksdb,tikv/rust-rocksdb): enable bot to control the reviewing flow
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#1104 config(tikv/pd): update reuqired status in pd branch release-5.4
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1105 opt(prow/cronjobs): split branch protection job to three jobs to speedup the running
  prow/cronjobs/branch-protector.yaml
Labels: size/L, lgtm, approved

#1106 feat(prow/config): limit the merge operation accounts
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#1107 config(tikv&tiflash): use new pipeline on 8.1 of tikv & tiflash
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1108 Update config.yaml
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1109 feat(ti-community/test-prow): add check rules for issue for han worlds
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/L, lgtm, approved

#1110 feat(ti-community/test-prow): add check rules for issue for han worlds (#1109)
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#1111 feat(prow/config): add issue title checker
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#1112 chore(prow/config): enable `issues` event type for format-checker plugin
  prow/config/plugins.yaml
Labels: lgtm, approved

#1113 chore(prow/configs): forbid label or unlabel cherry-pick type labels
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#1061 refactor(prow/config): refactor the labels to make persistent and unified
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  scripts/update-labels.sh
Labels: size/XXL, lgtm, approved

#1114 fix(prow/config): fix labels for doc repos
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1116 fix(prow/config): fix label color display
  prow/config/labels.md
  prow/config/labels.md.tmpl
  prow/config/labels.yaml
Labels: size/XXL, lgtm, approved

#1117 feat(tikv/client-c): enable prow bot for reviewing and merging
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/cronjobs/label-sync.yaml
Labels: size/L, lgtm, approved

#1118 config(tikv/tikv, pingcap/tiflash): update required status for release-7.5 branches
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1119 config(tikv & tiflash): update tikv & tiflash 7.1 required status
  prow/config/config.yaml
Labels: size/XS, lgtm, approved
