Repository ti-community-infra/configs, pull requests merged in 2024-06, with the labels that each got.

#1067 change the prow configuration for `pingcap/tidb-engine-ext` repository.
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1069 fix(tikv/*): enable DCO plugin
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1071 fix(tikv/*): fix dco config
  prow/config/plugins.yaml
Labels: lgtm, approved

#1073 Revert "fix(tikv/*): enable DCO plugin (#1069)"
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1074 Revert "Revert "fix(tikv/*): enable DCO plugin (#1069)""
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1076 config: enable new tidb-tools pipelines
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1077 To add the prefix "epic" to tikv/tiflow/tiflash.
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#1078 Add the prefix label impact to label the impact of the bug
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#1079 feat(prow/config): update config to support release-8.2 branches
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1081 config: avoid prow's "Merging to branch *** is forbidden" on 8.2
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1082 config: avoid prow's "Merging to branch *** is forbidden" on 8.2
  prow/config/config.yaml
Labels: size/XS, lgtm, approved
