Repository ti-community-infra/configs, pull requests merged in 2024-01, with the labels that each got.

#1013 chore(prow/configs): enable prioritize_existing_batches on `pingcap/tidb`
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1012 config: add release-7.6 branch configs
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1014 Revert "chore(prow/configs): enable prioritize_existing_batches on `pingcap/tidb`"
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1016 add: close test-repo need-cherry-pick label
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved

#1019 remove: test-prod dump key
  prow/config/plugins.yaml
Labels: size/XS, needs-ok-to-test, contribution, lgtm, approved

#1018 feat(pingcap/monitoring): use ti-chi-bot app to take over review control and automate merges
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#1020 add: do not need-cherry-pick label version list
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#1021 config(docs&docs-cn): update docs & docs-cn required status
  prow/config/config.yaml
Labels: size/M, lgtm, approved
