Repository ti-community-infra/configs, pull requests merged in 2024-11, with the labels that each got.

#1124 chore: support release 8.5
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/L, lgtm, approved

#1126 fix(prow/config): execlude `type/cherry-pick-for-*` labels when create cherry-pick PR
  prow/config/external_plugins_config.yaml
Labels: size/M, lgtm, approved

#1128 chore(prow/configs): delete useless labels
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, lgtm, approved

#1129 chore(prow/config): control affects type issue labels
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, lgtm, approved

#1131 fix(tikv/tikv): update branch protections
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1132 add fuzz-comp label
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/XS, ok-to-test, contribution, first-time-contributor, lgtm, approved
