Repository ti-community-infra/configs, pull requests merged in 2024-10, with the labels that each got.

#1121 chore(prow/config): support tidb release-8.4 branch
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
Labels: size/M, lgtm, approved

#1120 feat(prow/config): enable retest for failed github actions
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1122 Update external_plugins_config.yaml
  prow/config/external_plugins_config.yaml
Labels: lgtm, approved

#1123 config(tikv & tiflash): update required status for tikv&tiflash 6.5
  prow/config/config.yaml
Labels: size/XS, lgtm, approved
