Repository ti-community-infra/configs, pull requests merged in 2024-08, with the labels that each got.

#1092 chore(pingcap/tidb-tools): no need `ti-community-tar` plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1093 chore(pingcap/tiup): no need `ti-community-tar` plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1096 config: add release-8.3 config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, lgtm, approved

#1097 config: remove dmr version 8.2 config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, lgtm, approved

#1095 add `OWNERS` files to `tikv/client-go`
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1098 REQUEST: deploy prow for pingcap/tidb-dashboard
  prow/config/external_plugins_config.yaml
Labels: size/XS, lgtm, approved

#1099 feat(tikv/client-go): enable cherrypicker plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#1072 fix(tikv/pd): update branch protection rule for `master`
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1100 feat(tikv/client-rust): enable prow bot
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
  prow/cronjobs/label-sync.yaml
Labels: size/M, lgtm, approved

#1101 fix(pingcap/tidb-dashboard): forward event to cherrypicker external plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1102 feat(tikv/client-go,tikv/client-rust): add protection rules
  prow/config/config.yaml
Labels: size/S, lgtm, approved
