Repository ti-community-infra/configs, pull requests merged in 2024-07, with the labels that each got.

#1084 config(pingcap/tiflash): remove unnecessary branch protect status
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#1083 config(pd): update pd-release-branch-pt-with-tools-chunks
  prow/config/config.yaml
Labels: size/M, ok-to-test, contribution, first-time-contributor, lgtm, approved

#1085 delete found/customer and found/community, and add report/customer and report/community
  prow/config/external_plugins_config.yaml
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, first-time-contributor, lgtm, approved

#1086 config(pingcap/tidb-engine-ext): set tidb-engine-ext required context by tide
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1087 feat(tikv/raft-engine): enable trigger and common plugins
  prow/config/plugins.yaml
Labels: size/M, lgtm, approved

#1088 fix(ti-community-infra): make review approval act as lgtm
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1091 feat(tikv/raft-engine): enable reviewing controlling
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved
