Repository ti-community-infra/configs, pull requests merged in 2024-03, with the labels that each got.

#1029 fix(tikv/tikv): update branch protection rule
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1036 config: add config for branch release-8.0
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1037 config: remove dmr 7.6 config
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1038 Revert "chore(pingcap/community): disable auto merge by bot"
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1039 config(docs): add docs tidb operator release-1.6
  prow/config/external_plugins_config.yaml
Labels: size/XS, needs-ok-to-test, contribution, lgtm, approved
