Repository ti-community-infra/configs, pull requests merged in 2024-05, with the labels that each got.

#1058 config(pd): update pd-release-branch-pt to the correct chunk number
  prow/config/config.yaml
Labels: size/M, ok-to-test, contribution, lgtm, approved

#1056 config(tikv/community): enable `trigger` plugin
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1048 config(pd): update pd master required context
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#1059 chore(pingcap/tiflash): update merge template
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#1062 fix(pingcap-qe/ci): skip collaborators for lgtm for ci.git
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved
