Repository ti-community-infra/configs, pull requests merged in 2025-01, with the labels that each got.

#1135 remove cherry-pick labels for archived documentation
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/M, ok-to-test, contribution, lgtm, approved

#1137 chore(pingcap/tidb-engine-ext): deploy ti-community-cherry-pick plugin for pingcap/tidb-engine-ext
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1138 fix(pingcap/tidb-engine-ext): strict the merge user
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1139 config(tikv/pd): pd update required context on master
  prow/config/config.yaml
Labels: size/S, lgtm, approved

#1140 config(tikv/pd): adjust required context of tide on pd master branch
  prow/config/config.yaml
Labels: size/M, lgtm, approved

#1134 feat(pingcap/ticdc): add bot config for ticdc repo
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
  prow/config/plugins.yaml
  prow/cronjobs/label-sync.yaml
Labels: size/XL, lgtm, approved

#1141 config(tiflow): ticdc skip-unknown-contexts
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1142 config(ticdc): add build and ut as required context
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1143 fix(pingcap/ticdc): add config for issue-triage plugin
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1144 config(ticdc): update required status
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1145 fix(pingcap-inc/*): add merging templates for enterprise repos
  prow/config/config.yaml
Labels: size/S, lgtm, approved
