Repository ti-community-infra/configs, pull requests merged in 2025-07, with the labels that each got.

#1189 config(docs): add docs tidb operator release-2.0
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/XS, ok-to-test, contribution, lgtm, approved

#1195 chore(prow/configs): remove ti-community-tars plugin from pd repo configuration
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved

#1196 chore(prow/configs): update prow-tekton endpoint to el-github.ee-cd.svc
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved
