Repository ti-community-infra/configs, pull requests merged in 2025-03, with the labels that each got.

#1150 chore(tikv/tikv): remove tars plugin for tikv repo
  prow/config/external_plugins_config.yaml
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1152 prow/config: add "needs-cherry-pick-tidb-cloud"
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#1151 feat(configs): update bot config for 9.0 version series
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved

#1153 config(plugin-cherry_pick_unapproved): update regex to match release-9.0-beta.1
  prow/config/plugins.yaml
Labels: size/XS, lgtm, approved

#1154 prow/config: rename "tidb-cloud" label to "release-cloud"
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#1155 config(tikv/client-go): add additional required status checks for branch protection and update client-go settings
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1156 config(tikv/client-go): update required status checks of github action
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1157 config(docs): add release-cloud to branch protection and tide settings
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1159 chore(prow/configs): add license/cla to required status checks
  prow/config/config.yaml
Labels: size/XS, lgtm, approved

#1160 config(tikv/copr-test): add trigger support for tikv/copr-test
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
Labels: size/M, do-not-merge/hold, lgtm, approved

#1161 config(tikv/copr-test): add trigger plugin on tikv/copr-test
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S, lgtm, approved
