Repository ti-community-infra/configs, pull requests merged in 2025-02, with the labels that each got.

#1146 add branch protection for tidb-operator v2
  prow/config/config.yaml
Labels: size/S, ok-to-test, contribution, first-time-contributor, lgtm, approved

#1147 fix config in tidb operator v2
  prow/config/config.yaml
Labels: size/S, ok-to-test, contribution, lgtm, approved

#1149 chore(config): remove config for product v5.4.x versions
  prow/config/config.yaml
  prow/config/external_plugins_config.yaml
  prow/config/labels.md
  prow/config/labels.yaml
Labels: size/L, lgtm, approved
